name = "writer-app-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
GOOGLE_API_KEY = "AIzaSyDuHImCJP0XN4iVhGjJRbWB4zc9scxvyIw"

# Uncomment to use a custom domain
# routes = [
#   { pattern = "api.yourapp.com/*", zone_name = "yourapp.com" }
# ]
